version: '3'

services:
  cloud-ai-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloud-ai-app
    restart: unless-stopped
    ports:
      - "9000:9000"  # Port for Laravel
      - "5173:5173"  # Port for Vite
    environment:
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - APP_URL=${APP_URL}
      - ASSET_URL=${APP_URL}
      - APP_NAME=Cloud AI
      - LOG_CHANNEL=${LOG_CHANNEL}
      - DB_CONNECTION=pgsql
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-5435}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_SCHEMA=${DB_SCHEMA:-public}
      - CACHE_DRIVER=${CACHE_DRIVER:-file}
      - QUEUE_CONNECTION=${QUEUE_CONNECTION:-database}
      - SESSION_DRIVER=${SESSION_DRIVER:-database}
      - SESSION_LIFETIME=${SESSION_LIFETIME:-120}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - VITE_APP_NAME=Cloud AI
      - VITE_SSR=${VITE_SSR}
      - VIEW_COMPILED_PATH=/var/www/html/storage/framework/views
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cloud-ai.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.cloud-ai.entrypoints=websecure"
      - "traefik.http.routers.cloud-ai.tls.certresolver=le"
      - "traefik.http.services.cloud-ai.loadbalancer.server.port=80"
      - "traefik.http.services.cloud-ai.loadbalancer.healthcheck.path=/health-check"
      - "traefik.http.services.cloud-ai.loadbalancer.healthcheck.interval=10s"
      - "traefik.http.services.cloud-ai.loadbalancer.healthcheck.timeout=15s"
    volumes:
      - ./storage/app:/var/www/html/storage/app
      - ./storage/logs:/var/www/html/storage/logs
      - ./.env:/var/www/html/.env
    networks:
      - cloud-ai-network

networks:
  cloud-ai-network:
    driver: bridge
